### ISSUE TITLE
Broken detailed mesh

### ISSUE THREAD

**Issue by nerlfield** [radekd91/emoca#5]
When I run `demos/test_emoca_on_images.py --input_folder assets/ --output_folder results --model_name EMOCA --save_images True --save_codes True --save_mesh True`, it returns coarse and detailed meshes. 
![image](https://user-images.githubusercontent.com/23358975/163810451-ff74d51c-df42-44ed-a5bc-928814cfe647.png)
![image](https://user-images.githubusercontent.com/23358975/163810533-186019b7-750b-4a69-a494-dd22c2ed4826.png)

In the first image you can see the coarse mesh, it looks really good, but I want to go further and get the detailed mesh. As you can see, it's broken in the second image. Currently, I'm trying to fix that problem, but if you can give me insights about quick solution it would be great!

**Comment by radekd91** [comment]
So the detailed geometry seems to work in your case (as in the mesh is higher resolution) and has the correct shape. It seems the problem is with the texture which just turns black and white in your case. Maybe it is just the viewer you open it with? I have tested it in Meshlab and it should work fine (so it should be the detailed mesh with a texture). Can you try opening in Meshlab? @animtel
